/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePositionArgs } from "./CreatePositionArgs";
import { UpdatePositionArgs } from "./UpdatePositionArgs";
import { DeletePositionArgs } from "./DeletePositionArgs";
import { PositionCountArgs } from "./PositionCountArgs";
import { PositionFindManyArgs } from "./PositionFindManyArgs";
import { PositionFindUniqueArgs } from "./PositionFindUniqueArgs";
import { Position } from "./Position";
import { Flight } from "../../flight/base/Flight";
import { PositionService } from "../position.service";
@graphql.Resolver(() => Position)
export class PositionResolverBase {
  constructor(protected readonly service: PositionService) {}

  async _positionsMeta(
    @graphql.Args() args: PositionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Position])
  async positions(
    @graphql.Args() args: PositionFindManyArgs
  ): Promise<Position[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Position, { nullable: true })
  async position(
    @graphql.Args() args: PositionFindUniqueArgs
  ): Promise<Position | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Position)
  async createPosition(
    @graphql.Args() args: CreatePositionArgs
  ): Promise<Position> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        flight: {
          connect: args.data.flight,
        },
      },
    });
  }

  @graphql.Mutation(() => Position)
  async updatePosition(
    @graphql.Args() args: UpdatePositionArgs
  ): Promise<Position | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          flight: {
            connect: args.data.flight,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Position)
  async deletePosition(
    @graphql.Args() args: DeletePositionArgs
  ): Promise<Position | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Flight, {
    nullable: true,
    name: "flight",
  })
  async resolveFieldFlight(
    @graphql.Parent() parent: Position
  ): Promise<Flight | null> {
    const result = await this.service.getFlight(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
