/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlightService } from "../flight.service";
import { FlightCreateInput } from "./FlightCreateInput";
import { FlightWhereInput } from "./FlightWhereInput";
import { FlightWhereUniqueInput } from "./FlightWhereUniqueInput";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightUpdateInput } from "./FlightUpdateInput";
import { Flight } from "./Flight";
import { PositionFindManyArgs } from "../../position/base/PositionFindManyArgs";
import { Position } from "../../position/base/Position";
import { PositionWhereUniqueInput } from "../../position/base/PositionWhereUniqueInput";

export class FlightControllerBase {
  constructor(protected readonly service: FlightService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flight })
  async create(@common.Body() data: FlightCreateInput): Promise<Flight> {
    return await this.service.create({
      data: data,
      select: {
        aircraftType: true,
        createdAt: true,
        icao: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Flight] })
  @ApiNestedQuery(FlightFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Flight[]> {
    const args = plainToClass(FlightFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        aircraftType: true,
        createdAt: true,
        icao: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        aircraftType: true,
        createdAt: true,
        icao: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() data: FlightUpdateInput
  ): Promise<Flight | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          aircraftType: true,
          createdAt: true,
          icao: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          aircraftType: true,
          createdAt: true,
          icao: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/positions")
  @ApiNestedQuery(PositionFindManyArgs)
  async findManyPositions(
    @common.Req() request: Request,
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Position[]> {
    const query = plainToClass(PositionFindManyArgs, request.query);
    const results = await this.service.findPositions(params.id, {
      ...query,
      select: {
        createdAt: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        lat: true,
        lon: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/positions")
  async connectPositions(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PositionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/positions")
  async updatePositions(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PositionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/positions")
  async disconnectPositions(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: PositionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      positions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
