/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFlightArgs } from "./CreateFlightArgs";
import { UpdateFlightArgs } from "./UpdateFlightArgs";
import { DeleteFlightArgs } from "./DeleteFlightArgs";
import { FlightCountArgs } from "./FlightCountArgs";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightFindUniqueArgs } from "./FlightFindUniqueArgs";
import { Flight } from "./Flight";
import { PositionFindManyArgs } from "../../position/base/PositionFindManyArgs";
import { Position } from "../../position/base/Position";
import { FlightService } from "../flight.service";
@graphql.Resolver(() => Flight)
export class FlightResolverBase {
  constructor(protected readonly service: FlightService) {}

  async _flightsMeta(
    @graphql.Args() args: FlightCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Flight])
  async flights(@graphql.Args() args: FlightFindManyArgs): Promise<Flight[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Flight, { nullable: true })
  async flight(
    @graphql.Args() args: FlightFindUniqueArgs
  ): Promise<Flight | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Flight)
  async createFlight(@graphql.Args() args: CreateFlightArgs): Promise<Flight> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Flight)
  async updateFlight(
    @graphql.Args() args: UpdateFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Flight)
  async deleteFlight(
    @graphql.Args() args: DeleteFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Position], { name: "positions" })
  async resolveFieldPositions(
    @graphql.Parent() parent: Flight,
    @graphql.Args() args: PositionFindManyArgs
  ): Promise<Position[]> {
    const results = await this.service.findPositions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
